title:  Geometría analítica 4071
tagline:  Facultad de Ciencias, UNAM
author:
  name: 'Román Contreras'
  twitter:  

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

 google-ID: 'UA-104611849-2'

menu:
- {name: 'Información', url: 'info.html'}
- {name: 'Entradas', url: 'entradas.html'}
- {name: 'Ejercicios', url: 'ejercicios.html'}
- {name: 'Bibliografía', url: 'biblio.html'}
- {name: 'Contacto', url: 'contacto.html'}

social:
- {icon: 'github', link: 'https://www.github.com/romanbott'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:roman.contreras@ciencias.unam.mx'}

        # Available social icons are powered by Font Awesome, so you can use any icon that they offer
